spring:
  cloud:
    gateway:
      routed:
        - id: booking-details
          uri: lb://BOOKING-DETAILS
          predicates:
            - Path=/booking/**
          filters:
            - name: CircuitBreaker
              args:
                name: booking-details
                fallbackuri: forward:/bookingFallBack
        - id: Flight-details
          uri: lb://FLIGHT-DETAILS
          predicates:
            - Path=/flight/**
          filters:
            - name: CircuitBreaker
              args:
                name: flight-details
                fallbackuri: forward:/flightFallBack
        - id: Review
            uri: lb://REVIEW
            predicates:
              - Path=/review/**
            filters:
              - name: CircuitBreaker
                args:
                  name: Review
                  fallbackuri: forward:/reviewFallBack
        - id: login
            uri: lb://Login
            predicates:
              - Path=/login/**
            filters:
              - name: CircuitBreaker
                args:
                  name: login
                  fallbackuri: forward:/loginFallBack
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000